### ISSUE TITLE
expose as library

### ISSUE THREAD

**Issue by tcrayford** [Eun/goremovelines#1]
### Description

Hi! I have a tool that (for an internal use case), rewrites some code, but it currently leave blank lines extra in the generated body in several cases. I'd love to call `goremovelines` as a library to get rid of those lines - ideally there'd be a function that takes a `Mode` and an `ast.Node` and cleans it. Any chance you could expose the package as a library as well as a cli tool?

**Comment by Eun** [comment]
Hi, at the moment this is not planned. However the refactor should be fairy easy. Feel free to send a PR. :)
